### ISSUE TITLE
'after' expressions are not part of the language

### ISSUE THREAD

**Issue by frangio** [solidity-parser/antlr#14]
`after` is a reserved keyword but it isn't really used by the language as far as I know.

This part of the grammar seems wrong:

https://github.com/solidity-parser/antlr/blob/492c7f161300fb53d7206606595e36b0d95c20c6/Solidity.g4#L286

**Comment by fvictorio** [comment]
Thanks, fixed in 5ab4778231c09252844e23538ab082e319a89c8c
