### ISSUE TITLE
functionCall are recognized as expression instead of functionCall

### ISSUE THREAD

**Issue by azanux** [solidity-parser/antlr#26]
Is it a bug, or is there another way to visit functionCall instead of catching all expressions?

Function calls are recognized as expressions, so in the code source below:

```
contract Token {
    function transfer(address to, uint256 amount) public {
        // Transfer logic
    }
}

contract Vault {
    Token private token;

    function deposit(uint256 amount) public {
        token.transfer(address(this), amount);
    }

    function withdraw(uint256 amount) public {
        token.transfer(msg.sender, amount);
    }
}
```

The expression token.transfer(address(this), amount); generates the following AST:
```
statement
    simpleStatement
        expressionStatement
            expression
                expression
                    expression
                        primaryExpression
                            identifier
                                token
                    .
                    identifier
                        transfer
```

I made a change in the Solidity.g4 file at line 206 to have:
```
expressionStatement
    : ( functionCall | expression ) ';'
;
```

```
statement
    simpleStatement
        expressionStatement
            functionCall
                expression
                    expression
                        primaryExpression
                            identifier
                                token
                    .
                    identifier
                        transfer
```

**Comment by fvictorio** [comment]
Hmm, yes, this might be a mistake. The variants of `expression` don't use `functionCall` (although emit and revert do). I think I would add it there instead of adding it to `expressionStatement` though.

**Comment by azanux** [comment]
I noticed that Ethereum is currently maintaining the Solidity ANTLR grammar, so I will close the issue.

The official Solidity ANTLRV4 grammar can be found on the Ethereum GitHub repository
I will use  the Ethereum one,

Thanks for you reply ;-)

**Comment by fvictorio** [comment]
Yes, but just FYI that grammar is a per-version grammar, while this one is a more permissive one that should parse any solidity version. But if you only care about a single solidity version, then I'd recommend using the one maintained by them, since it's going to be way more tight.
