### ISSUE TITLE
Why not use the ANTLR grammar from the official `ethereum/solidity` repo?

### ISSUE THREAD

**Issue by nikitastupin** [solidity-parser/antlr#9]
Hey 👋 

First of all thank you for the project! It helped me to automate smart-contract analysis at scale.

I've just noticed that the official `ethereum/solidity` repo contains the ANTLR grammar for Solidity ([`SolidityParser.g4`](https://github.com/ethereum/solidity/blob/dea1b9ec7995ff7f16cdee7925a5858c5ce33982/docs/grammar/SolidityParser.g4)).

Is there any reason why we don't use the grammar from the official repo? Using it will keep the project up to date with latest language specification for zero effort.

**Comment by fvictorio** [comment]
IIRC the official grammar is stricter than this one. This grammar supports *any* solidity version (that is, it's very permissive), which is necessary for many projects that depend on this one.

That being said, I would love to stop maintaining this grammar, so any suggestions are welcome!

**Comment by nikitastupin** [comment]
Makes sense, thank you for the answer! I'll try out the official grammar on more or less huge scope and if it'll work I'll let you know :)
